// src/pages/admin/AdminDashboard.tsx
import { useEffect, useState } from 'react';
import {
  LayoutDashboard, FolderGit2, Zap, Newspaper, Mail,
  CheckCircle, XCircle, Clock, Loader2, Plus, Trash2,
  AlertCircle, LogOut, Eye, EyeOff
} from 'lucide-react';
import { supabase } from '../../lib/supabase';
import { useAuth } from '../../context/AuthContext';
import { useNavigation } from '../../context/NavigationContext';
import type { Project, Challenge, NewsPost, ContactMessage, NewsInsert } from '../../lib/database.types';
import Badge from '../../components/ui/Badge';
import Modal from '../../components/ui/Modal';

type Tab = 'overview' | 'projects' | 'challenges' | 'news' | 'messages';

const defaultNewsForm = { title: '', content: '', excerpt: '', image_url: '' };

export default function AdminDashboard() {
  const { user, signOut } = useAuth();
  const { navigate } = useNavigation();
  const [tab, setTab] = useState<Tab>('overview');
  const [projects, setProjects] = useState<Project[]>([]);
  const [challenges, setChallenges] = useState<Challenge[]>([]);
  const [news, setNews] = useState<NewsPost[]>([]);
  const [messages, setMessages] = useState<ContactMessage[]>([]);
  const [loading, setLoading] = useState(true);
  const [newsModalOpen, setNewsModalOpen] = useState(false);
  const [newsForm, setNewsForm] = useState(defaultNewsForm);
  const [newsSubmitting, setNewsSubmitting] = useState(false);
  const [newsError, setNewsError] = useState<string | null>(null);
  const [expandedMessage, setExpandedMessage] = useState<string | null>(null);

  useEffect(() => {
    if (!user) {
      navigate('admin-login');
      return;
    }
    fetchAll();
  }, [user]);

  async function fetchAll() {
    setLoading(true);
    const [p, c, n, m] = await Promise.all([
      supabase.from('projects').select('*').order('created_at', { ascending: false }),
      supabase.from('challenges').select('*').order('created_at', { ascending: false }),
      supabase.from('news').select('*').order('created_at', { ascending: false }),
      supabase.from('contact_messages').select('*').order('created_at', { ascending: false }),
    ]);
    if (p.data) setProjects(p.data);
    if (c.data) setChallenges(c.data);
    if (n.data) setNews(n.data);
    if (m.data) setMessages(m.data);
    setLoading(false);
  }

  async function updateProjectStatus(id: string, status: 'approved' | 'rejected') {
    await supabase.from('projects').update({ status }).eq('id', id);
    setProjects((prev) => prev.map((p) => p.id === id ? { ...p, status } : p));
  }

  async function updateChallengeStatus(id: string, status: 'approved' | 'rejected') {
    await supabase.from('challenges').update({ status }).eq('id', id);
    setChallenges((prev) => prev.map((c) => c.id === id ? { ...c, status } : c));
  }

  async function deleteNews(id: string) {
    await supabase.from('news').delete().eq('id', id);
    setNews((prev) => prev.filter((n) => n.id !== id));
  }

  async function submitNews(e: React.FormEvent) {
    e.preventDefault();
    if (!newsForm.title.trim() || !newsForm.content.trim()) {
      setNewsError('Titel en inhoud zijn verplicht.');
      return;
    }
    setNewsSubmitting(true);
    setNewsError(null);

    const insert: NewsInsert = {
      title: newsForm.title.trim(),
      content: newsForm.content.trim(),
      excerpt: newsForm.excerpt.trim(),
      image_url: newsForm.image_url.trim(),
    };

    const { data, error } = await supabase
      .from('news')
      .insert({ ...insert, author_id: user!.id })
      .select()
      .single();

    setNewsSubmitting(false);
    if (error) {
      setNewsError('Er ging iets mis.');
    } else {
      if (data) setNews((prev) => [data, ...prev]);
      setNewsForm(defaultNewsForm);
      setNewsModalOpen(false);
    }
  }

  const pendingProjects = projects.filter((p) => p.status === 'pending');
  const pendingChallenges = challenges.filter((c) => c.status === 'pending');

  const statusBadge = (status: string) => {
    if (status === 'approved') return <Badge variant="green">Goedgekeurd</Badge>;
    if (status === 'rejected') return <Badge variant="red">Afgewezen</Badge>;
    return <Badge variant="amber">In behandeling</Badge>;
  };

  const tabs: { id: Tab; label: string; icon: React.ElementType; count?: number }[] = [
    { id: 'overview', label: 'Overzicht', icon: LayoutDashboard },
    { id: 'projects', label: 'Projecten', icon: FolderGit2, count: pendingProjects.length || undefined },
    { id: 'challenges', label: 'Challenges', icon: Zap, count: pendingChallenges.length || undefined },
    { id: 'news', label: 'Nieuws', icon: Newspaper },
    { id: 'messages', label: 'Berichten', icon: Mail, count: messages.length || undefined },
  ];

  const inputClass = "w-full bg-white border border-gray-300 rounded-lg px-4 py-2.5 text-gray-900 placeholder-gray-400 text-sm focus:outline-none focus:border-roc-500 focus:ring-1 focus:ring-roc-500 transition-colors";

  if (!user) return null;

  return (
    <div className="min-h-screen bg-gray-50 pt-16">
      <div className="bg-white border-b border-gray-200 shadow-sm">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex items-center justify-between h-14">
            <div className="flex items-center gap-1 overflow-x-auto">
              {tabs.map(({ id, label, icon: Icon, count }) => (
                <button
                  key={id}
                  onClick={() => setTab(id)}
                  className={`flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-medium whitespace-nowrap transition-all ${
                    tab === id
                      ? 'bg-roc-50 text-roc-600 font-semibold'
                      : 'text-gray-500 hover:text-gray-900 hover:bg-gray-50'
                  }`}
                >
                  <Icon size={15} />
                  {label}
                  {count !== undefined && count > 0 && (
                    <span className="ml-1 bg-roc-500 text-white text-xs rounded-full px-1.5 py-0.5 leading-none">
                      {count}
                    </span>
                  )}
                </button>
              ))}
            </div>
            <button
              onClick={() => { signOut(); navigate('home'); }}
              className="flex items-center gap-2 text-sm text-gray-500 hover:text-roc-500 transition-colors ml-4"
            >
              <LogOut size={15} />
              <span className="hidden sm:inline">Uitloggen</span>
            </button>
          </div>
        </div>
      </div>

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        {loading ? (
          <div className="flex items-center justify-center py-24">
            <Loader2 size={32} className="text-roc-500 animate-spin" />
          </div>
        ) : (
          <>
            {tab === 'overview' && (
              <div className="space-y-8">
                <div>
                  <h1 className="text-2xl font-bold text-gray-900 mb-1">Dashboard</h1>
                  <p className="text-gray-500 text-sm">Welkom, {user.email}</p>
                </div>
                <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
                  {[
                    { label: 'Projecten wachtend', value: pendingProjects.length, icon: FolderGit2, color: 'text-amber-500', bg: 'bg-amber-50' },
                    { label: 'Challenges wachtend', value: pendingChallenges.length, icon: Zap, color: 'text-roc-500', bg: 'bg-roc-50' },
                    { label: 'Nieuwsberichten', value: news.length, icon: Newspaper, color: 'text-emerald-600', bg: 'bg-emerald-50' },
                    { label: 'Contactberichten', value: messages.length, icon: Mail, color: 'text-sky-600', bg: 'bg-sky-50' },
                  ].map(({ label, value, icon: Icon, color, bg }) => (
                    <div key={label} className="bg-white rounded-xl border border-gray-200 p-5 shadow-sm">
                      <div className={`w-10 h-10 ${bg} rounded-lg flex items-center justify-center mb-3`}>
                        <Icon size={18} className={color} />
                      </div>
                      <p className="text-3xl font-bold text-gray-900">{value}</p>
                      <p className="text-gray-500 text-xs mt-1">{label}</p>
                    </div>
                  ))}
                </div>

                {pendingProjects.length > 0 && (
                  <div>
                    <h2 className="text-gray-900 font-semibold mb-4 flex items-center gap-2">
                      <Clock size={16} className="text-amber-500" />
                      Projecten te beoordelen
                    </h2>
                    <div className="space-y-3">
                      {pendingProjects.slice(0, 3).map((p) => (
                        <div key={p.id} className="bg-white rounded-xl border border-gray-200 p-4 flex items-center justify-between gap-4 shadow-sm">
                          <div className="min-w-0">
                            <p className="text-gray-900 text-sm font-medium truncate">{p.title}</p>
                            <p className="text-gray-400 text-xs mt-0.5">door {p.author_name}</p>
                          </div>
                          <div className="flex items-center gap-2 flex-shrink-0">
                            <button onClick={() => updateProjectStatus(p.id, 'approved')} className="flex items-center gap-1.5 bg-emerald-50 hover:bg-emerald-100 text-emerald-700 px-3 py-1.5 rounded-lg text-xs font-medium transition-colors border border-emerald-200">
                              <CheckCircle size={13} /> Goedkeuren
                            </button>
                            <button onClick={() => updateProjectStatus(p.id, 'rejected')} className="flex items-center gap-1.5 bg-red-50 hover:bg-red-100 text-red-700 px-3 py-1.5 rounded-lg text-xs font-medium transition-colors border border-red-200">
                              <XCircle size={13} /> Afwijzen
                            </button>
                          </div>
                        </div>
                      ))}
                    </div>
                  </div>
                )}
              </div>
            )}

            {tab === 'projects' && (
              <div>
                <h2 className="text-xl font-bold text-gray-900 mb-6">Projecten Beheren</h2>
                <div className="space-y-3">
                  {projects.length === 0 ? (
                    <p className="text-gray-400 py-8 text-center">Geen projecten gevonden.</p>
                  ) : (
                    projects.map((p) => (
                      <div key={p.id} className="bg-white rounded-xl border border-gray-200 p-5 shadow-sm">
                        <div className="flex flex-col sm:flex-row sm:items-start justify-between gap-4">
                          <div className="min-w-0 flex-1">
                            <div className="flex items-center gap-2 mb-1 flex-wrap">
                              <span className="text-gray-900 font-medium text-sm">{p.title}</span>
                              {statusBadge(p.status)}
                            </div>
                            <p className="text-gray-400 text-xs mb-1">door {p.author_name} {p.author_email ? `(${p.author_email})` : ''}</p>
                            <p className="text-gray-500 text-xs line-clamp-2">{p.description}</p>
                            {p.tech_stack && p.tech_stack.length > 0 && (
                              <div className="flex flex-wrap gap-1 mt-2">
                                {p.tech_stack.slice(0, 5).map((t) => (
                                  <span key={t} className="px-2 py-0.5 bg-gray-100 rounded text-gray-600 text-xs">{t}</span>
                                ))}
                              </div>
                            )}
                          </div>
                          {p.status === 'pending' && (
                            <div className="flex items-center gap-2 flex-shrink-0">
                              <button onClick={() => updateProjectStatus(p.id, 'approved')} className="flex items-center gap-1.5 bg-emerald-50 hover:bg-emerald-100 text-emerald-700 px-3 py-1.5 rounded-lg text-xs font-medium transition-colors border border-emerald-200">
                                <CheckCircle size={13} /> Goedkeuren
                              </button>
                              <button onClick={() => updateProjectStatus(p.id, 'rejected')} className="flex items-center gap-1.5 bg-red-50 hover:bg-red-100 text-red-700 px-3 py-1.5 rounded-lg text-xs font-medium transition-colors border border-red-200">
                                <XCircle size={13} /> Afwijzen
                              </button>
                            </div>
                          )}
                        </div>
                      </div>
                    ))
                  )}
                </div>
              </div>
            )}

            {tab === 'challenges' && (
              <div>
                <h2 className="text-xl font-bold text-gray-900 mb-6">Challenges Beheren</h2>
                <div className="space-y-3">
                  {challenges.length === 0 ? (
                    <p className="text-gray-400 py-8 text-center">Geen challenges gevonden.</p>
                  ) : (
                    challenges.map((c) => (
                      <div key={c.id} className="bg-white rounded-xl border border-gray-200 p-5 shadow-sm">
                        <div className="flex flex-col sm:flex-row sm:items-start justify-between gap-4">
                          <div className="min-w-0 flex-1">
                            <div className="flex items-center gap-2 mb-1 flex-wrap">
                              <span className="text-gray-900 font-medium text-sm">{c.title}</span>
                              {statusBadge(c.status)}
                            </div>
                            <p className="text-gray-400 text-xs mb-1">{c.company_name}{c.contact_email ? ` - ${c.contact_email}` : ''}</p>
                            <p className="text-gray-500 text-xs line-clamp-2">{c.description}</p>
                          </div>
                          {c.status === 'pending' && (
                            <div className="flex items-center gap-2 flex-shrink-0">
                              <button onClick={() => updateChallengeStatus(c.id, 'approved')} className="flex items-center gap-1.5 bg-emerald-50 hover:bg-emerald-100 text-emerald-700 px-3 py-1.5 rounded-lg text-xs font-medium transition-colors border border-emerald-200">
                                <CheckCircle size={13} /> Goedkeuren
                              </button>
                              <button onClick={() => updateChallengeStatus(c.id, 'rejected')} className="flex items-center gap-1.5 bg-red-50 hover:bg-red-100 text-red-700 px-3 py-1.5 rounded-lg text-xs font-medium transition-colors border border-red-200">
                                <XCircle size={13} /> Afwijzen
                              </button>
                            </div>
                          )}
                        </div>
                      </div>
                    ))
                  )}
                </div>
              </div>
            )}

            {tab === 'news' && (
              <div>
                <div className="flex items-center justify-between mb-6">
                  <h2 className="text-xl font-bold text-gray-900">Nieuws Beheren</h2>
                  <button
                    onClick={() => { setNewsModalOpen(true); setNewsError(null); }}
                    className="flex items-center gap-2 bg-roc-500 hover:bg-roc-600 text-white px-4 py-2 rounded-lg text-sm font-semibold transition-colors"
                  >
                    <Plus size={16} />
                    Nieuwsbericht
                  </button>
                </div>
                <div className="space-y-3">
                  {news.length === 0 ? (
                    <p className="text-gray-400 py-8 text-center">Nog geen nieuwsberichten.</p>
                  ) : (
                    news.map((n) => (
                      <div key={n.id} className="bg-white rounded-xl border border-gray-200 p-5 flex items-start justify-between gap-4 shadow-sm">
                        <div className="min-w-0 flex-1">
                          <p className="text-gray-900 font-medium text-sm mb-1">{n.title}</p>
                          {n.excerpt && <p className="text-gray-400 text-xs line-clamp-1">{n.excerpt}</p>}
                          <p className="text-gray-300 text-xs mt-1">
                            {new Date(n.created_at).toLocaleDateString('nl-NL', { day: 'numeric', month: 'long', year: 'numeric' })}
                          </p>
                        </div>
                        <button
                          onClick={() => deleteNews(n.id)}
                          className="flex items-center gap-1.5 bg-red-50 hover:bg-red-100 text-red-700 px-3 py-1.5 rounded-lg text-xs font-medium transition-colors border border-red-200 flex-shrink-0"
                        >
                          <Trash2 size={13} /> Verwijderen
                        </button>
                      </div>
                    ))
                  )}
                </div>
              </div>
            )}

            {tab === 'messages' && (
              <div>
                <h2 className="text-xl font-bold text-gray-900 mb-6">Contactberichten</h2>
                <div className="space-y-3">
                  {messages.length === 0 ? (
                    <p className="text-gray-400 py-8 text-center">Geen contactberichten.</p>
                  ) : (
                    messages.map((m) => (
                      <div key={m.id} className="bg-white rounded-xl border border-gray-200 p-5 shadow-sm">
                        <div className="flex items-start justify-between gap-4">
                          <div className="min-w-0 flex-1">
                            <div className="flex items-center gap-3 mb-1 flex-wrap">
                              <span className="text-gray-900 font-medium text-sm">{m.name}</span>
                              <span className="text-gray-400 text-xs">{m.email}</span>
                            </div>
                            <p className="text-gray-700 text-sm font-medium mb-1">{m.subject}</p>
                            {expandedMessage === m.id ? (
                              <p className="text-gray-500 text-sm leading-relaxed">{m.message}</p>
                            ) : (
                              <p className="text-gray-400 text-xs line-clamp-2">{m.message}</p>
                            )}
                          </div>
                          <button
                            onClick={() => setExpandedMessage(expandedMessage === m.id ? null : m.id)}
                            className="flex items-center gap-1.5 bg-gray-50 hover:bg-gray-100 text-gray-600 px-3 py-1.5 rounded-lg text-xs font-medium transition-colors border border-gray-200 flex-shrink-0"
                          >
                            {expandedMessage === m.id ? <EyeOff size={13} /> : <Eye size={13} />}
                            {expandedMessage === m.id ? 'Inklappen' : 'Lees meer'}
                          </button>
                        </div>
                        <p className="text-gray-300 text-xs mt-3">
                          {new Date(m.created_at).toLocaleDateString('nl-NL', { day: 'numeric', month: 'long', year: 'numeric', hour: '2-digit', minute: '2-digit' })}
                        </p>
                      </div>
                    ))
                  )}
                </div>
              </div>
            )}
          </>
        )}
      </div>

      <Modal
        isOpen={newsModalOpen}
        onClose={() => { setNewsModalOpen(false); setNewsError(null); setNewsForm(defaultNewsForm); }}
        title="Nieuwsbericht Plaatsen"
      >
        <form onSubmit={submitNews} className="space-y-5">
          {newsError && (
            <div className="flex items-center gap-2 bg-red-50 border border-red-200 rounded-lg p-3 text-red-600 text-sm">
              <AlertCircle size={16} />
              {newsError}
            </div>
          )}

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1.5">Titel <span className="text-red-500">*</span></label>
            <input type="text" required value={newsForm.title} onChange={(e) => setNewsForm({ ...newsForm, title: e.target.value })} placeholder="Titel van het nieuwsbericht" className={inputClass} />
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1.5">Samenvatting</label>
            <input type="text" value={newsForm.excerpt} onChange={(e) => setNewsForm({ ...newsForm, excerpt: e.target.value })} placeholder="Korte samenvatting (optioneel)" className={inputClass} />
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1.5">Inhoud <span className="text-red-500">*</span></label>
            <textarea required rows={6} value={newsForm.content} onChange={(e) => setNewsForm({ ...newsForm, content: e.target.value })} placeholder="Schrijf hier de volledige inhoud..." className={`${inputClass} resize-none`} />
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1.5">Afbeelding URL</label>
            <input type="url" value={newsForm.image_url} onChange={(e) => setNewsForm({ ...newsForm, image_url: e.target.value })} placeholder="https://images.pexels.com/..." className={inputClass} />
          </div>

          <button
            type="submit"
            disabled={newsSubmitting}
            className="w-full flex items-center justify-center gap-2 bg-roc-500 hover:bg-roc-600 disabled:bg-roc-300 text-white px-6 py-3 rounded-xl font-semibold transition-all"
          >
            {newsSubmitting ? <><Loader2 size={18} className="animate-spin" />Plaatsen...</> : <><Newspaper size={18} />Nieuwsbericht Plaatsen</>}
          </button>
        </form>
      </Modal>
    </div>
  );
}

// src/pages/admin/AdminDashboard.vue
<script setup lang="ts">
import { ref, computed, onMounted, onBeforeUnmount, watchEffect } from 'vue'
import { useRouter } from 'vue-router'
import {
  LayoutDashboard, FolderGit2, Zap, Newspaper, Mail,
  CircleCheck as CheckCircle, Circle as XCircle, Clock, Loader as Loader2,
  Plus, Trash2, CircleAlert as AlertCircle, LogOut, Eye, EyeOff, Hop as Home,
} from 'lucide-vue-next'
import { supabase } from '../../lib/supabase'
import { useAuth } from '../../composables/useAuth'
import type { Project, Challenge, NewsItem } from '../../types'
import Badge from '../../components/ui/Badge.vue'
import Modal from '../../components/ui/Modal.vue'

interface ContactMessage {
  id: string
  name: string
  email: string
  subject: string
  message: string
  created_at: string
}

type Tab = 'overview' | 'projects' | 'challenges' | 'news' | 'messages'

const router = useRouter()
const { user, signOut } = useAuth()

const tab = ref<Tab>('overview')
const projects = ref<Project[]>([])
const challenges = ref<Challenge[]>([])
const news = ref<NewsItem[]>([])
const messages = ref<ContactMessage[]>([])
const loading = ref(true)
const newsModalOpen = ref(false)
const newsForm = ref({ title: '', content: '', excerpt: '', image_url: '' })
const newsSubmitting = ref(false)
const newsError = ref<string | null>(null)
const expandedMessage = ref<string | null>(null)

watchEffect(() => {
  if (user.value === null && !loading.value) {
    router.replace({ name: 'admin-login' })
  }
})

const fetchProjects = async () => {
  const { data } = await supabase.from('projects').select('*').order('created_at', { ascending: false })
  if (data) projects.value = data as Project[]
}
const fetchChallenges = async () => {
  const { data } = await supabase.from('challenges').select('*').order('created_at', { ascending: false })
  if (data) challenges.value = data as Challenge[]
}
const fetchNews = async () => {
  const { data } = await supabase.from('news').select('*').order('created_at', { ascending: false })
  if (data) news.value = data as NewsItem[]
}
const fetchMessages = async () => {
  const { data } = await supabase.from('contact_messages').select('*').order('created_at', { ascending: false })
  if (data) messages.value = data as ContactMessage[]
}
const fetchAll = async () => {
  loading.value = true
  await Promise.all([fetchProjects(), fetchChallenges(), fetchNews(), fetchMessages()])
  loading.value = false
}

let channels: ReturnType<typeof supabase.channel>[] = []

onMounted(() => {
  if (!user.value) {
    router.replace({ name: 'admin-login' })
    return
  }
  fetchAll()

  channels = [
    supabase.channel('admin-projects').on('postgres_changes', { event: '*', schema: 'public', table: 'projects' }, fetchProjects).subscribe(),
    supabase.channel('admin-challenges').on('postgres_changes', { event: '*', schema: 'public', table: 'challenges' }, fetchChallenges).subscribe(),
    supabase.channel('admin-news').on('postgres_changes', { event: '*', schema: 'public', table: 'news' }, fetchNews).subscribe(),
    supabase.channel('admin-messages').on('postgres_changes', { event: '*', schema: 'public', table: 'contact_messages' }, fetchMessages).subscribe(),
  ]
})

onBeforeUnmount(() => {
  channels.forEach((c) => supabase.removeChannel(c))
})

const updateProjectStatus = async (id: string, status: 'approved' | 'rejected') => {
  await supabase.from('projects').update({ status }).eq('id', id)
  projects.value = projects.value.map((p) => p.id === id ? { ...p, status } : p)
}
const updateChallengeStatus = async (id: string, status: 'approved' | 'rejected') => {
  await supabase.from('challenges').update({ status }).eq('id', id)
  challenges.value = challenges.value.map((c) => c.id === id ? { ...c, status } : c)
}
const deleteNews = async (id: string) => {
  await supabase.from('news').delete().eq('id', id)
  news.value = news.value.filter((n) => n.id !== id)
}
const deleteProject = async (id: string) => {
  await supabase.from('projects').delete().eq('id', id)
  projects.value = projects.value.filter((p) => p.id !== id)
}
const deleteChallenge = async (id: string) => {
  await supabase.from('challenges').delete().eq('id', id)
  challenges.value = challenges.value.filter((c) => c.id !== id)
}

const submitNews = async (e: Event) => {
  e.preventDefault()
  if (!newsForm.value.title.trim() || !newsForm.value.content.trim()) {
    newsError.value = 'Titel en inhoud zijn verplicht.'
    return
  }
  newsSubmitting.value = true
  newsError.value = null

  const { data, error } = await supabase
    .from('news')
    .insert({
      title: newsForm.value.title.trim(),
      content: newsForm.value.content.trim(),
      excerpt: newsForm.value.excerpt.trim(),
      image_url: newsForm.value.image_url.trim(),
      author_id: user.value!.id,
    })
    .select()
    .single()

  newsSubmitting.value = false
  if (error) {
    newsError.value = 'Er ging iets mis. Probeer het opnieuw.'
  } else {
    if (data) news.value = [data as NewsItem, ...news.value]
    newsForm.value = { title: '', content: '', excerpt: '', image_url: '' }
    newsModalOpen.value = false
  }
}

const pendingProjects = computed(() => projects.value.filter((p) => p.status === 'pending'))
const pendingChallenges = computed(() => challenges.value.filter((c) => c.status === 'pending'))
const unreadMessages = computed(() => messages.value.length)

const statusVariant = (status: string): 'green' | 'red' | 'amber' => {
  if (status === 'approved') return 'green'
  if (status === 'rejected') return 'red'
  return 'amber'
}
const statusLabel = (status: string) => {
  if (status === 'approved') return 'Goedgekeurd'
  if (status === 'rejected') return 'Afgewezen'
  return 'In behandeling'
}

const tabs = computed(() => [
  { id: 'overview' as Tab, label: 'Overzicht', icon: LayoutDashboard, count: undefined as number | undefined },
  { id: 'projects' as Tab, label: 'Projecten', icon: FolderGit2, count: pendingProjects.value.length || undefined },
  { id: 'challenges' as Tab, label: 'Challenges', icon: Zap, count: pendingChallenges.value.length || undefined },
  { id: 'news' as Tab, label: 'Nieuws', icon: Newspaper, count: undefined as number | undefined },
  { id: 'messages' as Tab, label: 'Berichten', icon: Mail, count: unreadMessages.value || undefined },
])

const overviewCards = computed(() => [
  { label: 'Projecten te beoordelen', value: pendingProjects.value.length, icon: FolderGit2, color: 'text-amber-500', bg: 'bg-amber-50', tab: 'projects' as Tab },
  { label: 'Challenges te beoordelen', value: pendingChallenges.value.length, icon: Zap, color: 'text-roc-500', bg: 'bg-roc-50', tab: 'challenges' as Tab },
  { label: 'Nieuwsberichten', value: news.value.length, icon: Newspaper, color: 'text-emerald-600', bg: 'bg-emerald-50', tab: 'news' as Tab },
  { label: 'Contactberichten', value: messages.value.length, icon: Mail, color: 'text-sky-600', bg: 'bg-sky-50', tab: 'messages' as Tab },
])

const goHome = () => router.push({ name: 'home' })
const doSignOut = async () => {
  await signOut()
  router.push({ name: 'home' })
}
const closeNewsModal = () => {
  newsModalOpen.value = false
  newsError.value = null
  newsForm.value = { title: '', content: '', excerpt: '', image_url: '' }
}

const inputClass = 'w-full bg-white border border-gray-200 rounded-xl px-4 py-2.5 text-gray-900 placeholder-gray-400 text-sm focus:outline-none focus:border-roc-500 focus:ring-1 focus:ring-roc-500 transition-colors'

const fmtDate = (d: string) => new Date(d).toLocaleDateString('nl-NL')
const fmtDateLong = (d: string) => new Date(d).toLocaleDateString('nl-NL', { day: 'numeric', month: 'long', year: 'numeric' })
const fmtDateTime = (d: string) => new Date(d).toLocaleDateString('nl-NL', { day: 'numeric', month: 'long', year: 'numeric', hour: '2-digit', minute: '2-digit' })

const toggleMessage = (id: string) => {
  expandedMessage.value = expandedMessage.value === id ? null : id
}
</script>

<template>
  <div v-if="user" class="min-h-screen bg-gray-50">
    <div class="bg-white border-b border-gray-200 shadow-sm sticky top-0 z-40">
      <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="flex items-center justify-between h-16">
          <div class="flex items-center gap-4">
            <img src="/image.png" alt="ROC van Flevoland" class="h-10 w-auto" />
            <span class="text-sm font-semibold text-gray-400 hidden sm:block">Beheerderspaneel</span>
          </div>
          <div class="flex items-center gap-2">
            <button class="flex items-center gap-1.5 text-sm text-gray-500 hover:text-gray-900 transition-colors px-3 py-2 rounded-lg hover:bg-gray-50" @click="goHome">
              <Home :size="15" />
              <span class="hidden sm:inline">Naar site</span>
            </button>
            <button class="flex items-center gap-1.5 text-sm text-gray-500 hover:text-roc-500 transition-colors px-3 py-2 rounded-lg hover:bg-roc-50" @click="doSignOut">
              <LogOut :size="15" />
              <span class="hidden sm:inline">Uitloggen</span>
            </button>
          </div>
        </div>
      </div>
    </div>

    <div class="bg-white border-b border-gray-100">
      <div class="max-w-7xl mx-auto px-2 sm:px-6 lg:px-8">
        <div class="flex items-center gap-0.5 overflow-x-auto scrollbar-none" style="scrollbar-width: none">
          <button
            v-for="t in tabs" :key="t.id"
            :class="['flex items-center gap-1.5 px-3 sm:px-4 py-3.5 text-xs sm:text-sm font-medium whitespace-nowrap border-b-2 transition-all', tab === t.id ? 'border-roc-500 text-roc-600' : 'border-transparent text-gray-400 hover:text-gray-900 hover:border-gray-200']"
            @click="tab = t.id"
          >
            <component :is="t.icon" :size="15" />
            {{ t.label }}
            <span v-if="t.count !== undefined && t.count > 0" class="ml-0.5 bg-roc-500 text-white text-xs rounded-full px-1.5 py-0.5 leading-none font-bold">
              {{ t.count }}
            </span>
          </button>
        </div>
      </div>
    </div>

    <div class="max-w-7xl mx-auto px-3 sm:px-6 lg:px-8 py-6 sm:py-8">
      <div v-if="loading" class="flex items-center justify-center py-24">
        <Loader2 :size="32" class="text-roc-500 animate-spin" />
      </div>

      <template v-else>
        <div v-if="tab === 'overview'" class="space-y-8">
          <div>
            <h1 class="text-2xl font-bold text-gray-900 mb-0.5">Dashboard</h1>
            <p class="text-gray-400 text-sm">Ingelogd als {{ user.email }}</p>
          </div>

          <div class="grid grid-cols-2 sm:grid-cols-2 lg:grid-cols-4 gap-3 sm:gap-4">
            <button
              v-for="card in overviewCards" :key="card.label"
              class="bg-white rounded-xl border border-gray-200 p-5 shadow-sm text-left hover:shadow-md hover:border-gray-300 transition-all"
              @click="tab = card.tab"
            >
              <div :class="['w-10 h-10 rounded-xl flex items-center justify-center mb-3', card.bg]">
                <component :is="card.icon" :size="18" :class="card.color" />
              </div>
              <p class="text-3xl font-bold text-gray-900">{{ card.value }}</p>
              <p class="text-gray-400 text-xs mt-1">{{ card.label }}</p>
            </button>
          </div>

          <div v-if="pendingProjects.length > 0 || pendingChallenges.length > 0" class="space-y-6">
            <div v-if="pendingProjects.length > 0">
              <h2 class="text-gray-900 font-semibold mb-3 flex items-center gap-2 text-sm">
                <Clock :size="15" class="text-amber-500" />
                Projecten wachtend op goedkeuring
              </h2>
              <div class="space-y-2">
                <div v-for="p in pendingProjects.slice(0, 5)" :key="p.id" class="bg-white rounded-xl border border-amber-100 p-4 flex items-center justify-between gap-4 shadow-sm">
                  <div class="min-w-0">
                    <p class="text-gray-900 text-sm font-semibold truncate">{{ p.title }}</p>
                    <p class="text-gray-400 text-xs mt-0.5">door {{ p.author_name }} · {{ fmtDate(p.created_at) }}</p>
                  </div>
                  <div class="flex items-center gap-2 flex-shrink-0">
                    <button class="flex items-center gap-1.5 bg-emerald-50 hover:bg-emerald-100 text-emerald-700 px-3 py-1.5 rounded-lg text-xs font-semibold transition-colors border border-emerald-200" @click="updateProjectStatus(p.id, 'approved')">
                      <CheckCircle :size="12" /> Goedkeuren
                    </button>
                    <button class="flex items-center gap-1.5 bg-red-50 hover:bg-red-100 text-red-700 px-3 py-1.5 rounded-lg text-xs font-semibold transition-colors border border-red-200" @click="updateProjectStatus(p.id, 'rejected')">
                      <XCircle :size="12" /> Afwijzen
                    </button>
                  </div>
                </div>
              </div>
            </div>

            <div v-if="pendingChallenges.length > 0">
              <h2 class="text-gray-900 font-semibold mb-3 flex items-center gap-2 text-sm">
                <Clock :size="15" class="text-roc-500" />
                Challenges wachtend op goedkeuring
              </h2>
              <div class="space-y-2">
                <div v-for="c in pendingChallenges.slice(0, 5)" :key="c.id" class="bg-white rounded-xl border border-roc-100 p-4 flex items-center justify-between gap-4 shadow-sm">
                  <div class="min-w-0">
                    <p class="text-gray-900 text-sm font-semibold truncate">{{ c.title }}</p>
                    <p class="text-gray-400 text-xs mt-0.5">{{ c.company_name }} · {{ fmtDate(c.created_at) }}</p>
                  </div>
                  <div class="flex items-center gap-2 flex-shrink-0">
                    <button class="flex items-center gap-1.5 bg-emerald-50 hover:bg-emerald-100 text-emerald-700 px-3 py-1.5 rounded-lg text-xs font-semibold transition-colors border border-emerald-200" @click="updateChallengeStatus(c.id, 'approved')">
                      <CheckCircle :size="12" /> Goedkeuren
                    </button>
                    <button class="flex items-center gap-1.5 bg-red-50 hover:bg-red-100 text-red-700 px-3 py-1.5 rounded-lg text-xs font-semibold transition-colors border border-red-200" @click="updateChallengeStatus(c.id, 'rejected')">
                      <XCircle :size="12" /> Afwijzen
                    </button>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div v-if="pendingProjects.length === 0 && pendingChallenges.length === 0" class="bg-white rounded-xl border border-gray-200 p-8 text-center">
            <CheckCircle :size="32" class="text-emerald-400 mx-auto mb-3" />
            <p class="font-semibold text-gray-700">Alles bijgewerkt</p>
            <p class="text-sm text-gray-400 mt-1">Er zijn geen inzendingen die wachten op goedkeuring.</p>
          </div>
        </div>

        <div v-else-if="tab === 'projects'">
          <div class="flex items-center justify-between mb-6">
            <div>
              <h2 class="text-xl font-bold text-gray-900">Projecten</h2>
              <p class="text-sm text-gray-400 mt-0.5">{{ projects.length }} totaal · {{ pendingProjects.length }} wachtend</p>
            </div>
          </div>
          <div class="space-y-3">
            <div v-if="projects.length === 0" class="text-center py-16 text-gray-400">
              <FolderGit2 :size="40" class="mx-auto mb-3 opacity-30" />
              <p class="font-medium">Geen projecten gevonden.</p>
            </div>
            <div v-for="p in projects" v-else :key="p.id" class="bg-white rounded-xl border border-gray-200 p-5 shadow-sm">
              <div class="flex flex-col sm:flex-row sm:items-start justify-between gap-4">
                <div class="min-w-0 flex-1">
                  <div class="flex items-center gap-2 mb-1 flex-wrap">
                    <span class="text-gray-900 font-semibold text-sm">{{ p.title }}</span>
                    <Badge :variant="statusVariant(p.status)">{{ statusLabel(p.status) }}</Badge>
                  </div>
                  <p class="text-gray-400 text-xs mb-2">
                    door <span class="font-medium text-gray-600">{{ p.author_name }}</span>
                    <template v-if="p.author_email"> ({{ p.author_email }})</template> · {{ fmtDate(p.created_at) }}
                  </p>
                  <p class="text-gray-500 text-xs line-clamp-2 leading-relaxed">{{ p.description }}</p>
                  <div v-if="p.tech_stack && p.tech_stack.length > 0" class="flex flex-wrap gap-1 mt-2">
                    <span v-for="t in p.tech_stack.slice(0, 6)" :key="t" class="px-2 py-0.5 bg-gray-100 rounded-full text-gray-600 text-xs">{{ t }}</span>
                  </div>
                </div>
                <div class="flex items-center gap-2 flex-shrink-0">
                  <template v-if="p.status === 'pending'">
                    <button class="flex items-center gap-1.5 bg-emerald-50 hover:bg-emerald-100 text-emerald-700 px-3 py-1.5 rounded-lg text-xs font-semibold transition-colors border border-emerald-200" @click="updateProjectStatus(p.id, 'approved')">
                      <CheckCircle :size="12" /> Goedkeuren
                    </button>
                    <button class="flex items-center gap-1.5 bg-red-50 hover:bg-red-100 text-red-700 px-3 py-1.5 rounded-lg text-xs font-semibold transition-colors border border-red-200" @click="updateProjectStatus(p.id, 'rejected')">
                      <XCircle :size="12" /> Afwijzen
                    </button>
                  </template>
                  <button class="flex items-center gap-1.5 bg-gray-50 hover:bg-red-50 text-gray-400 hover:text-red-600 px-2.5 py-1.5 rounded-lg text-xs transition-colors border border-gray-200 hover:border-red-200" @click="deleteProject(p.id)">
                    <Trash2 :size="12" />
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div v-else-if="tab === 'challenges'">
          <div class="flex items-center justify-between mb-6">
            <div>
              <h2 class="text-xl font-bold text-gray-900">Challenges</h2>
              <p class="text-sm text-gray-400 mt-0.5">{{ challenges.length }} totaal · {{ pendingChallenges.length }} wachtend</p>
            </div>
          </div>
          <div class="space-y-3">
            <div v-if="challenges.length === 0" class="text-center py-16 text-gray-400">
              <Zap :size="40" class="mx-auto mb-3 opacity-30" />
              <p class="font-medium">Geen challenges gevonden.</p>
            </div>
            <div v-for="c in challenges" v-else :key="c.id" class="bg-white rounded-xl border border-gray-200 p-5 shadow-sm">
              <div class="flex flex-col sm:flex-row sm:items-start justify-between gap-4">
                <div class="min-w-0 flex-1">
                  <div class="flex items-center gap-2 mb-1 flex-wrap">
                    <span class="text-gray-900 font-semibold text-sm">{{ c.title }}</span>
                    <Badge :variant="statusVariant(c.status)">{{ statusLabel(c.status) }}</Badge>
                  </div>
                  <p class="text-gray-400 text-xs mb-2">
                    <span class="font-medium text-gray-600">{{ c.company_name }}</span>
                    <template v-if="c.contact_email"> · {{ c.contact_email }}</template> · {{ fmtDate(c.created_at) }}
                  </p>
                  <p class="text-gray-500 text-xs line-clamp-2 leading-relaxed">{{ c.description }}</p>
                  <span v-if="c.prize" class="inline-block mt-2 text-xs font-semibold text-amber-700 bg-amber-50 px-2 py-0.5 rounded-full">{{ c.prize }}</span>
                </div>
                <div class="flex items-center gap-2 flex-shrink-0">
                  <template v-if="c.status === 'pending'">
                    <button class="flex items-center gap-1.5 bg-emerald-50 hover:bg-emerald-100 text-emerald-700 px-3 py-1.5 rounded-lg text-xs font-semibold transition-colors border border-emerald-200" @click="updateChallengeStatus(c.id, 'approved')">
                      <CheckCircle :size="12" /> Goedkeuren
                    </button>
                    <button class="flex items-center gap-1.5 bg-red-50 hover:bg-red-100 text-red-700 px-3 py-1.5 rounded-lg text-xs font-semibold transition-colors border border-red-200" @click="updateChallengeStatus(c.id, 'rejected')">
                      <XCircle :size="12" /> Afwijzen
                    </button>
                  </template>
                  <button class="flex items-center gap-1.5 bg-gray-50 hover:bg-red-50 text-gray-400 hover:text-red-600 px-2.5 py-1.5 rounded-lg text-xs transition-colors border border-gray-200 hover:border-red-200" @click="deleteChallenge(c.id)">
                    <Trash2 :size="12" />
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div v-else-if="tab === 'news'">
          <div class="flex items-center justify-between mb-6">
            <div>
              <h2 class="text-xl font-bold text-gray-900">Nieuws</h2>
              <p class="text-sm text-gray-400 mt-0.5">{{ news.length }} berichten</p>
            </div>
            <button
              class="flex items-center gap-2 bg-roc-500 hover:bg-roc-600 text-white px-4 py-2.5 rounded-xl text-sm font-semibold transition-colors"
              @click="newsModalOpen = true; newsError = null"
            >
              <Plus :size="15" />
              Nieuwsbericht
            </button>
          </div>
          <div class="space-y-3">
            <div v-if="news.length === 0" class="text-center py-16 text-gray-400">
              <Newspaper :size="40" class="mx-auto mb-3 opacity-30" />
              <p class="font-medium">Nog geen nieuwsberichten.</p>
              <p class="text-xs mt-1">Klik op "Nieuwsbericht" om te beginnen.</p>
            </div>
            <div v-for="n in news" v-else :key="n.id" class="bg-white rounded-xl border border-gray-200 p-5 shadow-sm flex gap-4">
              <img v-if="n.image_url" :src="n.image_url" :alt="n.title" class="w-20 h-16 rounded-lg object-cover flex-shrink-0" />
              <div class="flex-1 min-w-0">
                <p class="text-gray-900 font-semibold text-sm mb-0.5">{{ n.title }}</p>
                <p v-if="n.excerpt" class="text-gray-400 text-xs line-clamp-1 mb-1">{{ n.excerpt }}</p>
                <p class="text-gray-300 text-xs">{{ fmtDateLong(n.created_at) }}</p>
              </div>
              <button
                class="flex items-center gap-1.5 bg-red-50 hover:bg-red-100 text-red-600 px-3 py-1.5 rounded-lg text-xs font-medium transition-colors border border-red-200 flex-shrink-0 self-start"
                @click="deleteNews(n.id)"
              >
                <Trash2 :size="12" /> Verwijderen
              </button>
            </div>
          </div>
        </div>

        <div v-else-if="tab === 'messages'">
          <div class="mb-6">
            <h2 class="text-xl font-bold text-gray-900">Contactberichten</h2>
            <p class="text-sm text-gray-400 mt-0.5">{{ messages.length }} berichten</p>
          </div>
          <div class="space-y-3">
            <div v-if="messages.length === 0" class="text-center py-16 text-gray-400">
              <Mail :size="40" class="mx-auto mb-3 opacity-30" />
              <p class="font-medium">Geen contactberichten.</p>
            </div>
            <div v-for="m in messages" v-else :key="m.id" class="bg-white rounded-xl border border-gray-200 p-5 shadow-sm">
              <div class="flex items-start justify-between gap-4">
                <div class="min-w-0 flex-1">
                  <div class="flex items-center gap-3 mb-0.5 flex-wrap">
                    <span class="text-gray-900 font-semibold text-sm">{{ m.name }}</span>
                    <a :href="`mailto:${m.email}`" class="text-roc-500 text-xs hover:underline">{{ m.email }}</a>
                  </div>
                  <p v-if="m.subject" class="text-gray-700 text-sm font-medium mb-2">{{ m.subject }}</p>
                  <p v-if="expandedMessage === m.id" class="text-gray-500 text-sm leading-relaxed">{{ m.message }}</p>
                  <p v-else class="text-gray-400 text-xs line-clamp-2">{{ m.message }}</p>
                </div>
                <button
                  class="flex items-center gap-1.5 bg-gray-50 hover:bg-gray-100 text-gray-500 px-3 py-1.5 rounded-lg text-xs font-medium transition-colors border border-gray-200 flex-shrink-0"
                  @click="toggleMessage(m.id)"
                >
                  <EyeOff v-if="expandedMessage === m.id" :size="12" />
                  <Eye v-else :size="12" />
                  {{ expandedMessage === m.id ? 'Inklappen' : 'Lees meer' }}
                </button>
              </div>
              <p class="text-gray-300 text-xs mt-3">{{ fmtDateTime(m.created_at) }}</p>
            </div>
          </div>
        </div>
      </template>
    </div>

    <Modal :is-open="newsModalOpen" title="Nieuwsbericht Plaatsen" @close="closeNewsModal">
      <form class="space-y-5" @submit="submitNews">
        <div v-if="newsError" class="flex items-center gap-2 bg-red-50 border border-red-200 rounded-lg p-3 text-red-600 text-sm">
          <AlertCircle :size="16" />
          {{ newsError }}
        </div>
        <div>
          <label class="block text-sm font-medium text-gray-700 mb-1.5">Titel <span class="text-red-500">*</span></label>
          <input v-model="newsForm.title" type="text" required placeholder="Titel van het nieuwsbericht" :class="inputClass" />
        </div>
        <div>
          <label class="block text-sm font-medium text-gray-700 mb-1.5">Samenvatting</label>
          <input v-model="newsForm.excerpt" type="text" placeholder="Korte samenvatting (optioneel)" :class="inputClass" />
        </div>
        <div>
          <label class="block text-sm font-medium text-gray-700 mb-1.5">Inhoud <span class="text-red-500">*</span></label>
          <textarea v-model="newsForm.content" required :rows="6" placeholder="Schrijf hier de volledige inhoud..." :class="`${inputClass} resize-none`" />
        </div>
        <div>
          <label class="block text-sm font-medium text-gray-700 mb-1.5">Afbeelding URL</label>
          <input v-model="newsForm.image_url" type="url" placeholder="https://images.pexels.com/..." :class="inputClass" />
        </div>
        <button
          type="submit" :disabled="newsSubmitting"
          class="w-full flex items-center justify-center gap-2 bg-roc-500 hover:bg-roc-600 disabled:bg-roc-300 text-white px-6 py-3 rounded-xl font-semibold transition-all"
        >
          <template v-if="newsSubmitting"><Loader2 :size="18" class="animate-spin" />Plaatsen...</template>
          <template v-else><Newspaper :size="18" />Nieuwsbericht Plaatsen</template>
        </button>
      </form>
    </Modal>
  </div>
</template>
