// src/pages/AdminDashboard.tsx
import { useState, useEffect } from 'react';
import { CircleCheck as CheckCircle, Circle as XCircle, Clock, LayoutDashboard, LogOut } from 'lucide-react';
import { supabase } from '../lib/supabase';
import type { Project, Challenge } from '../types';
import { useAuth } from '../context/AuthContext';
import { useNavigation } from '../context/NavigationContext';

type Tab = 'projecten' | 'challenges';

export function AdminDashboard() {
  const { user, signOut } = useAuth();
  const { navigate } = useNavigation();
  const [tab, setTab] = useState<Tab>('projecten');
  const [projects, setProjects] = useState<Project[]>([]);
  const [challenges, setChallenges] = useState<Challenge[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (!user) { navigate('home'); return; }
    fetchAll();
  }, [user]);

  const fetchAll = async () => {
    setLoading(true);
    const [{ data: p }, { data: c }] = await Promise.all([
      supabase.from('projects').select('*').order('created_at', { ascending: false }),
      supabase.from('challenges').select('*').order('created_at', { ascending: false }),
    ]);
    setProjects(p ?? []);
    setChallenges(c ?? []);
    setLoading(false);
  };

  const updateProject = async (id: string, status: 'approved' | 'rejected') => {
    await supabase.from('projects').update({ status }).eq('id', id);
    setProjects((prev) => prev.map((p) => p.id === id ? { ...p, status } : p));
  };

  const updateChallenge = async (id: string, status: 'approved' | 'rejected') => {
    await supabase.from('challenges').update({ status }).eq('id', id);
    setChallenges((prev) => prev.map((c) => c.id === id ? { ...c, status } : c));
  };

  const statusBadge = (status: string) => {
    if (status === 'approved') return <span className="text-xs font-semibold bg-green-50 text-green-700 px-2.5 py-1 rounded-full flex items-center gap-1"><CheckCircle size={11} />Goedgekeurd</span>;
    if (status === 'rejected') return <span className="text-xs font-semibold bg-red-50 text-red-700 px-2.5 py-1 rounded-full flex items-center gap-1"><XCircle size={11} />Afgewezen</span>;
    return <span className="text-xs font-semibold bg-amber-50 text-amber-700 px-2.5 py-1 rounded-full flex items-center gap-1"><Clock size={11} />In behandeling</span>;
  };

  if (!user) return null;

  const pending = {
    projecten: projects.filter((p) => p.status === 'pending').length,
    challenges: challenges.filter((c) => c.status === 'pending').length,
  };

  return (
    <div className="min-h-screen bg-gray-50">
      <div className="bg-white border-b border-gray-100 sticky top-0 z-40">
        <div className="max-w-6xl mx-auto px-6 py-4 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-9 h-9 rounded-full bg-roc-500 flex items-center justify-center">
              <LayoutDashboard size={16} className="text-white" />
            </div>
            <div>
              <p className="text-sm font-bold text-gray-900">Admin Dashboard</p>
              <p className="text-xs text-gray-400">{user.email}</p>
            </div>
          </div>
          <button
            onClick={() => { signOut(); navigate('home'); }}
            className="flex items-center gap-2 text-sm text-gray-500 hover:text-red-600 transition-colors px-3 py-1.5 rounded-full hover:bg-red-50"
          >
            <LogOut size={15} />
            Uitloggen
          </button>
        </div>
      </div>

      <div className="max-w-6xl mx-auto px-6 py-8">
        <div className="grid grid-cols-3 gap-4 mb-8">
          {[
            { label: 'Projecten', value: projects.length, pending: pending.projecten },
            { label: 'Challenges', value: challenges.length, pending: pending.challenges },
            { label: 'In behandeling', value: pending.projecten + pending.challenges, pending: 0 },
          ].map(({ label, value, pending: p }) => (
            <div key={label} className="bg-white rounded-2xl p-5 border border-gray-100">
              <p className="text-xs font-semibold text-gray-400 uppercase tracking-wide mb-1">{label}</p>
              <p className="text-3xl font-bold text-gray-900">{value}</p>
              {p > 0 && <p className="text-xs text-amber-600 font-medium mt-1">{p} wacht op beoordeling</p>}
            </div>
          ))}
        </div>

        <div className="bg-white rounded-2xl border border-gray-100 overflow-hidden">
          <div className="flex border-b border-gray-100">
            {(['projecten', 'challenges'] as Tab[]).map((t) => (
              <button
                key={t}
                onClick={() => setTab(t)}
                className={`flex-1 py-4 text-sm font-semibold transition-colors capitalize relative ${
                  tab === t ? 'text-roc-500' : 'text-gray-400 hover:text-gray-700'
                }`}
              >
                {t.charAt(0).toUpperCase() + t.slice(1)}
                {pending[t] > 0 && (
                  <span className="ml-2 bg-amber-500 text-white text-xs rounded-full w-5 h-5 inline-flex items-center justify-center">
                    {pending[t]}
                  </span>
                )}
                {tab === t && <div className="absolute bottom-0 left-0 right-0 h-0.5 bg-roc-500" />}
              </button>
            ))}
          </div>

          {loading ? (
            <div className="p-6 space-y-3">
              {[1,2,3].map((i) => <div key={i} className="h-16 bg-gray-100 rounded-xl animate-pulse" />)}
            </div>
          ) : (
            <div className="divide-y divide-gray-100">
              {(tab === 'projecten' ? projects : challenges).map((item) => (
                <div key={item.id} className="p-5 flex items-center justify-between gap-4">
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-3 mb-1">
                      {statusBadge(item.status)}
                      <h3 className="font-semibold text-gray-900 truncate">{item.title}</h3>
                    </div>
                    <p className="text-xs text-gray-400">
                      {tab === 'projecten'
                        ? `door ${'author_name' in item ? item.author_name : ''}`
                        : `door ${'company_name' in item ? item.company_name : ''}`
                      } · {new Date(item.created_at).toLocaleDateString('nl-NL')}
                    </p>
                  </div>
                  {item.status === 'pending' && (
                    <div className="flex gap-2 shrink-0">
                      <button
                        onClick={() => tab === 'projecten' ? updateProject(item.id, 'approved') : updateChallenge(item.id, 'approved')}
                        className="flex items-center gap-1.5 bg-green-50 hover:bg-green-100 text-green-700 text-xs font-semibold px-3 py-2 rounded-full transition-colors"
                      >
                        <CheckCircle size={13} /> Goedkeuren
                      </button>
                      <button
                        onClick={() => tab === 'projecten' ? updateProject(item.id, 'rejected') : updateChallenge(item.id, 'rejected')}
                        className="flex items-center gap-1.5 bg-red-50 hover:bg-red-100 text-red-700 text-xs font-semibold px-3 py-2 rounded-full transition-colors"
                      >
                        <XCircle size={13} /> Afwijzen
                      </button>
                    </div>
                  )}
                </div>
              ))}
              {(tab === 'projecten' ? projects : challenges).length === 0 && (
                <div className="p-10 text-center text-gray-400 text-sm">Geen items gevonden</div>
              )}
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

// src/pages/admin/AdminDashboard.vue
<script setup lang="ts">
import { ref, computed, onMounted, onBeforeUnmount, watchEffect } from 'vue'
import { useRouter } from 'vue-router'
import {
  LayoutDashboard, FolderGit2, Zap, Newspaper, Mail,
  CircleCheck as CheckCircle, Circle as XCircle, Clock, Loader as Loader2,
  Plus, Trash2, CircleAlert as AlertCircle, LogOut, Eye, EyeOff, Hop as Home,
} from 'lucide-vue-next'
import { supabase } from '../../lib/supabase'
import { useAuth } from '../../composables/useAuth'
import type { Project, Challenge, NewsItem } from '../../types'
import Badge from '../../components/ui/Badge.vue'
import Modal from '../../components/ui/Modal.vue'

interface ContactMessage {
  id: string
  name: string
  email: string
  subject: string
  message: string
  created_at: string
}

type Tab = 'overview' | 'projects' | 'challenges' | 'news' | 'messages'

const router = useRouter()
const { user, signOut } = useAuth()

const tab = ref<Tab>('overview')
const projects = ref<Project[]>([])
const challenges = ref<Challenge[]>([])
const news = ref<NewsItem[]>([])
const messages = ref<ContactMessage[]>([])
const loading = ref(true)
const newsModalOpen = ref(false)
const newsForm = ref({ title: '', content: '', excerpt: '', image_url: '' })
const newsSubmitting = ref(false)
const newsError = ref<string | null>(null)
const expandedMessage = ref<string | null>(null)

watchEffect(() => {
  if (user.value === null && !loading.value) {
    router.replace({ name: 'admin-login' })
  }
})

const fetchProjects = async () => {
  const { data } = await supabase.from('projects').select('*').order('created_at', { ascending: false })
  if (data) projects.value = data as Project[]
}
const fetchChallenges = async () => {
  const { data } = await supabase.from('challenges').select('*').order('created_at', { ascending: false })
  if (data) challenges.value = data as Challenge[]
}
const fetchNews = async () => {
  const { data } = await supabase.from('news').select('*').order('created_at', { ascending: false })
  if (data) news.value = data as NewsItem[]
}
const fetchMessages = async () => {
  const { data } = await supabase.from('contact_messages').select('*').order('created_at', { ascending: false })
  if (data) messages.value = data as ContactMessage[]
}
const fetchAll = async () => {
  loading.value = true
  await Promise.all([fetchProjects(), fetchChallenges(), fetchNews(), fetchMessages()])
  loading.value = false
}

let channels: ReturnType<typeof supabase.channel>[] = []

onMounted(() => {
  if (!user.value) {
    router.replace({ name: 'admin-login' })
    return
  }
  fetchAll()

  channels = [
    supabase.channel('admin-projects').on('postgres_changes', { event: '*', schema: 'public', table: 'projects' }, fetchProjects).subscribe(),
    supabase.channel('admin-challenges').on('postgres_changes', { event: '*', schema: 'public', table: 'challenges' }, fetchChallenges).subscribe(),
    supabase.channel('admin-news').on('postgres_changes', { event: '*', schema: 'public', table: 'news' }, fetchNews).subscribe(),
    supabase.channel('admin-messages').on('postgres_changes', { event: '*', schema: 'public', table: 'contact_messages' }, fetchMessages).subscribe(),
  ]
})

onBeforeUnmount(() => {
  channels.forEach((c) => supabase.removeChannel(c))
})

const updateProjectStatus = async (id: string, status: 'approved' | 'rejected') => {
  await supabase.from('projects').update({ status }).eq('id', id)
  projects.value = projects.value.map((p) => p.id === id ? { ...p, status } : p)
}
const updateChallengeStatus = async (id: string, status: 'approved' | 'rejected') => {
  await supabase.from('challenges').update({ status }).eq('id', id)
  challenges.value = challenges.value.map((c) => c.id === id ? { ...c, status } : c)
}
const deleteNews = async (id: string) => {
  await supabase.from('news').delete().eq('id', id)
  news.value = news.value.filter((n) => n.id !== id)
}
const deleteProject = async (id: string) => {
  await supabase.from('projects').delete().eq('id', id)
  projects.value = projects.value.filter((p) => p.id !== id)
}
const deleteChallenge = async (id: string) => {
  await supabase.from('challenges').delete().eq('id', id)
  challenges.value = challenges.value.filter((c) => c.id !== id)
}

const submitNews = async (e: Event) => {
  e.preventDefault()
  if (!newsForm.value.title.trim() || !newsForm.value.content.trim()) {
    newsError.value = 'Titel en inhoud zijn verplicht.'
    return
  }
  newsSubmitting.value = true
  newsError.value = null

  const { data, error } = await supabase
    .from('news')
    .insert({
      title: newsForm.value.title.trim(),
      content: newsForm.value.content.trim(),
      excerpt: newsForm.value.excerpt.trim(),
      image_url: newsForm.value.image_url.trim(),
      author_id: user.value!.id,
    })
    .select()
    .single()

  newsSubmitting.value = false
  if (error) {
    newsError.value = 'Er ging iets mis. Probeer het opnieuw.'
  } else {
    if (data) news.value = [data as NewsItem, ...news.value]
    newsForm.value = { title: '', content: '', excerpt: '', image_url: '' }
    newsModalOpen.value = false
  }
}

const pendingProjects = computed(() => projects.value.filter((p) => p.status === 'pending'))
const pendingChallenges = computed(() => challenges.value.filter((c) => c.status === 'pending'))
const unreadMessages = computed(() => messages.value.length)

const statusVariant = (status: string): 'green' | 'red' | 'amber' => {
  if (status === 'approved') return 'green'
  if (status === 'rejected') return 'red'
  return 'amber'
}
const statusLabel = (status: string) => {
  if (status === 'approved') return 'Goedgekeurd'
  if (status === 'rejected') return 'Afgewezen'
  return 'In behandeling'
}

const tabs = computed(() => [
  { id: 'overview' as Tab, label: 'Overzicht', icon: LayoutDashboard, count: undefined as number | undefined },
  { id: 'projects' as Tab, label: 'Projecten', icon: FolderGit2, count: pendingProjects.value.length || undefined },
  { id: 'challenges' as Tab, label: 'Challenges', icon: Zap, count: pendingChallenges.value.length || undefined },
  { id: 'news' as Tab, label: 'Nieuws', icon: Newspaper, count: undefined as number | undefined },
  { id: 'messages' as Tab, label: 'Berichten', icon: Mail, count: unreadMessages.value || undefined },
])

const overviewCards = computed(() => [
  { label: 'Projecten te beoordelen', value: pendingProjects.value.length, icon: FolderGit2, color: 'text-amber-500', bg: 'bg-amber-50', tab: 'projects' as Tab },
  { label: 'Challenges te beoordelen', value: pendingChallenges.value.length, icon: Zap, color: 'text-roc-500', bg: 'bg-roc-50', tab: 'challenges' as Tab },
  { label: 'Nieuwsberichten', value: news.value.length, icon: Newspaper, color: 'text-emerald-600', bg: 'bg-emerald-50', tab: 'news' as Tab },
  { label: 'Contactberichten', value: messages.value.length, icon: Mail, color: 'text-sky-600', bg: 'bg-sky-50', tab: 'messages' as Tab },
])

const goHome = () => router.push({ name: 'home' })
const doSignOut = async () => {
  await signOut()
  router.push({ name: 'home' })
}
const closeNewsModal = () => {
  newsModalOpen.value = false
  newsError.value = null
  newsForm.value = { title: '', content: '', excerpt: '', image_url: '' }
}

const inputClass = 'w-full bg-white border border-gray-200 rounded-xl px-4 py-2.5 text-gray-900 placeholder-gray-400 text-sm focus:outline-none focus:border-roc-500 focus:ring-1 focus:ring-roc-500 transition-colors'

const fmtDate = (d: string) => new Date(d).toLocaleDateString('nl-NL')
const fmtDateLong = (d: string) => new Date(d).toLocaleDateString('nl-NL', { day: 'numeric', month: 'long', year: 'numeric' })
const fmtDateTime = (d: string) => new Date(d).toLocaleDateString('nl-NL', { day: 'numeric', month: 'long', year: 'numeric', hour: '2-digit', minute: '2-digit' })

const toggleMessage = (id: string) => {
  expandedMessage.value = expandedMessage.value === id ? null : id
}
</script>

<template>
  <div v-if="user" class="min-h-screen bg-gray-50">
    <div class="bg-white border-b border-gray-200 shadow-sm sticky top-0 z-40">
      <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="flex items-center justify-between h-16">
          <div class="flex items-center gap-4">
            <img src="/image.png" alt="ROC van Flevoland" class="h-10 w-auto" />
            <span class="text-sm font-semibold text-gray-400 hidden sm:block">Beheerderspaneel</span>
          </div>
          <div class="flex items-center gap-2">
            <button class="flex items-center gap-1.5 text-sm text-gray-500 hover:text-gray-900 transition-colors px-3 py-2 rounded-lg hover:bg-gray-50" @click="goHome">
              <Home :size="15" />
              <span class="hidden sm:inline">Naar site</span>
            </button>
            <button class="flex items-center gap-1.5 text-sm text-gray-500 hover:text-roc-500 transition-colors px-3 py-2 rounded-lg hover:bg-roc-50" @click="doSignOut">
              <LogOut :size="15" />
              <span class="hidden sm:inline">Uitloggen</span>
            </button>
          </div>
        </div>
      </div>
    </div>

    <div class="bg-white border-b border-gray-100">
      <div class="max-w-7xl mx-auto px-2 sm:px-6 lg:px-8">
        <div class="flex items-center gap-0.5 overflow-x-auto scrollbar-none" style="scrollbar-width: none">
          <button
            v-for="t in tabs" :key="t.id"
            :class="['flex items-center gap-1.5 px-3 sm:px-4 py-3.5 text-xs sm:text-sm font-medium whitespace-nowrap border-b-2 transition-all', tab === t.id ? 'border-roc-500 text-roc-600' : 'border-transparent text-gray-400 hover:text-gray-900 hover:border-gray-200']"
            @click="tab = t.id"
          >
            <component :is="t.icon" :size="15" />
            {{ t.label }}
            <span v-if="t.count !== undefined && t.count > 0" class="ml-0.5 bg-roc-500 text-white text-xs rounded-full px-1.5 py-0.5 leading-none font-bold">
              {{ t.count }}
            </span>
          </button>
        </div>
      </div>
    </div>

    <div class="max-w-7xl mx-auto px-3 sm:px-6 lg:px-8 py-6 sm:py-8">
      <div v-if="loading" class="flex items-center justify-center py-24">
        <Loader2 :size="32" class="text-roc-500 animate-spin" />
      </div>

      <template v-else>
        <div v-if="tab === 'overview'" class="space-y-8">
          <div>
            <h1 class="text-2xl font-bold text-gray-900 mb-0.5">Dashboard</h1>
            <p class="text-gray-400 text-sm">Ingelogd als {{ user.email }}</p>
          </div>

          <div class="grid grid-cols-2 sm:grid-cols-2 lg:grid-cols-4 gap-3 sm:gap-4">
            <button
              v-for="card in overviewCards" :key="card.label"
              class="bg-white rounded-xl border border-gray-200 p-5 shadow-sm text-left hover:shadow-md hover:border-gray-300 transition-all"
              @click="tab = card.tab"
            >
              <div :class="['w-10 h-10 rounded-xl flex items-center justify-center mb-3', card.bg]">
                <component :is="card.icon" :size="18" :class="card.color" />
              </div>
              <p class="text-3xl font-bold text-gray-900">{{ card.value }}</p>
              <p class="text-gray-400 text-xs mt-1">{{ card.label }}</p>
            </button>
          </div>

          <div v-if="pendingProjects.length > 0 || pendingChallenges.length > 0" class="space-y-6">
            <div v-if="pendingProjects.length > 0">
              <h2 class="text-gray-900 font-semibold mb-3 flex items-center gap-2 text-sm">
                <Clock :size="15" class="text-amber-500" />
                Projecten wachtend op goedkeuring
              </h2>
              <div class="space-y-2">
                <div v-for="p in pendingProjects.slice(0, 5)" :key="p.id" class="bg-white rounded-xl border border-amber-100 p-4 flex items-center justify-between gap-4 shadow-sm">
                  <div class="min-w-0">
                    <p class="text-gray-900 text-sm font-semibold truncate">{{ p.title }}</p>
                    <p class="text-gray-400 text-xs mt-0.5">door {{ p.author_name }} · {{ fmtDate(p.created_at) }}</p>
                  </div>
                  <div class="flex items-center gap-2 flex-shrink-0">
                    <button class="flex items-center gap-1.5 bg-emerald-50 hover:bg-emerald-100 text-emerald-700 px-3 py-1.5 rounded-lg text-xs font-semibold transition-colors border border-emerald-200" @click="updateProjectStatus(p.id, 'approved')">
                      <CheckCircle :size="12" /> Goedkeuren
                    </button>
                    <button class="flex items-center gap-1.5 bg-red-50 hover:bg-red-100 text-red-700 px-3 py-1.5 rounded-lg text-xs font-semibold transition-colors border border-red-200" @click="updateProjectStatus(p.id, 'rejected')">
                      <XCircle :size="12" /> Afwijzen
                    </button>
                  </div>
                </div>
              </div>
            </div>

            <div v-if="pendingChallenges.length > 0">
              <h2 class="text-gray-900 font-semibold mb-3 flex items-center gap-2 text-sm">
                <Clock :size="15" class="text-roc-500" />
                Challenges wachtend op goedkeuring
              </h2>
              <div class="space-y-2">
                <div v-for="c in pendingChallenges.slice(0, 5)" :key="c.id" class="bg-white rounded-xl border border-roc-100 p-4 flex items-center justify-between gap-4 shadow-sm">
                  <div class="min-w-0">
                    <p class="text-gray-900 text-sm font-semibold truncate">{{ c.title }}</p>
                    <p class="text-gray-400 text-xs mt-0.5">{{ c.company_name }} · {{ fmtDate(c.created_at) }}</p>
                  </div>
                  <div class="flex items-center gap-2 flex-shrink-0">
                    <button class="flex items-center gap-1.5 bg-emerald-50 hover:bg-emerald-100 text-emerald-700 px-3 py-1.5 rounded-lg text-xs font-semibold transition-colors border border-emerald-200" @click="updateChallengeStatus(c.id, 'approved')">
                      <CheckCircle :size="12" /> Goedkeuren
                    </button>
                    <button class="flex items-center gap-1.5 bg-red-50 hover:bg-red-100 text-red-700 px-3 py-1.5 rounded-lg text-xs font-semibold transition-colors border border-red-200" @click="updateChallengeStatus(c.id, 'rejected')">
                      <XCircle :size="12" /> Afwijzen
                    </button>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div v-if="pendingProjects.length === 0 && pendingChallenges.length === 0" class="bg-white rounded-xl border border-gray-200 p-8 text-center">
            <CheckCircle :size="32" class="text-emerald-400 mx-auto mb-3" />
            <p class="font-semibold text-gray-700">Alles bijgewerkt</p>
            <p class="text-sm text-gray-400 mt-1">Er zijn geen inzendingen die wachten op goedkeuring.</p>
          </div>
        </div>

        <div v-else-if="tab === 'projects'">
          <div class="flex items-center justify-between mb-6">
            <div>
              <h2 class="text-xl font-bold text-gray-900">Projecten</h2>
              <p class="text-sm text-gray-400 mt-0.5">{{ projects.length }} totaal · {{ pendingProjects.length }} wachtend</p>
            </div>
          </div>
          <div class="space-y-3">
            <div v-if="projects.length === 0" class="text-center py-16 text-gray-400">
              <FolderGit2 :size="40" class="mx-auto mb-3 opacity-30" />
              <p class="font-medium">Geen projecten gevonden.</p>
            </div>
            <div v-for="p in projects" v-else :key="p.id" class="bg-white rounded-xl border border-gray-200 p-5 shadow-sm">
              <div class="flex flex-col sm:flex-row sm:items-start justify-between gap-4">
                <div class="min-w-0 flex-1">
                  <div class="flex items-center gap-2 mb-1 flex-wrap">
                    <span class="text-gray-900 font-semibold text-sm">{{ p.title }}</span>
                    <Badge :variant="statusVariant(p.status)">{{ statusLabel(p.status) }}</Badge>
                  </div>
                  <p class="text-gray-400 text-xs mb-2">
                    door <span class="font-medium text-gray-600">{{ p.author_name }}</span>
                    <template v-if="p.author_email"> ({{ p.author_email }})</template> · {{ fmtDate(p.created_at) }}
                  </p>
                  <p class="text-gray-500 text-xs line-clamp-2 leading-relaxed">{{ p.description }}</p>
                  <div v-if="p.tech_stack && p.tech_stack.length > 0" class="flex flex-wrap gap-1 mt-2">
                    <span v-for="t in p.tech_stack.slice(0, 6)" :key="t" class="px-2 py-0.5 bg-gray-100 rounded-full text-gray-600 text-xs">{{ t }}</span>
                  </div>
                </div>
                <div class="flex items-center gap-2 flex-shrink-0">
                  <template v-if="p.status === 'pending'">
                    <button class="flex items-center gap-1.5 bg-emerald-50 hover:bg-emerald-100 text-emerald-700 px-3 py-1.5 rounded-lg text-xs font-semibold transition-colors border border-emerald-200" @click="updateProjectStatus(p.id, 'approved')">
                      <CheckCircle :size="12" /> Goedkeuren
                    </button>
                    <button class="flex items-center gap-1.5 bg-red-50 hover:bg-red-100 text-red-700 px-3 py-1.5 rounded-lg text-xs font-semibold transition-colors border border-red-200" @click="updateProjectStatus(p.id, 'rejected')">
                      <XCircle :size="12" /> Afwijzen
                    </button>
                  </template>
                  <button class="flex items-center gap-1.5 bg-gray-50 hover:bg-red-50 text-gray-400 hover:text-red-600 px-2.5 py-1.5 rounded-lg text-xs transition-colors border border-gray-200 hover:border-red-200" @click="deleteProject(p.id)">
                    <Trash2 :size="12" />
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div v-else-if="tab === 'challenges'">
          <div class="flex items-center justify-between mb-6">
            <div>
              <h2 class="text-xl font-bold text-gray-900">Challenges</h2>
              <p class="text-sm text-gray-400 mt-0.5">{{ challenges.length }} totaal · {{ pendingChallenges.length }} wachtend</p>
            </div>
          </div>
          <div class="space-y-3">
            <div v-if="challenges.length === 0" class="text-center py-16 text-gray-400">
              <Zap :size="40" class="mx-auto mb-3 opacity-30" />
              <p class="font-medium">Geen challenges gevonden.</p>
            </div>
            <div v-for="c in challenges" v-else :key="c.id" class="bg-white rounded-xl border border-gray-200 p-5 shadow-sm">
              <div class="flex flex-col sm:flex-row sm:items-start justify-between gap-4">
                <div class="min-w-0 flex-1">
                  <div class="flex items-center gap-2 mb-1 flex-wrap">
                    <span class="text-gray-900 font-semibold text-sm">{{ c.title }}</span>
                    <Badge :variant="statusVariant(c.status)">{{ statusLabel(c.status) }}</Badge>
                  </div>
                  <p class="text-gray-400 text-xs mb-2">
                    <span class="font-medium text-gray-600">{{ c.company_name }}</span>
                    <template v-if="c.contact_email"> · {{ c.contact_email }}</template> · {{ fmtDate(c.created_at) }}
                  </p>
                  <p class="text-gray-500 text-xs line-clamp-2 leading-relaxed">{{ c.description }}</p>
                  <span v-if="c.prize" class="inline-block mt-2 text-xs font-semibold text-amber-700 bg-amber-50 px-2 py-0.5 rounded-full">{{ c.prize }}</span>
                </div>
                <div class="flex items-center gap-2 flex-shrink-0">
                  <template v-if="c.status === 'pending'">
                    <button class="flex items-center gap-1.5 bg-emerald-50 hover:bg-emerald-100 text-emerald-700 px-3 py-1.5 rounded-lg text-xs font-semibold transition-colors border border-emerald-200" @click="updateChallengeStatus(c.id, 'approved')">
                      <CheckCircle :size="12" /> Goedkeuren
                    </button>
                    <button class="flex items-center gap-1.5 bg-red-50 hover:bg-red-100 text-red-700 px-3 py-1.5 rounded-lg text-xs font-semibold transition-colors border border-red-200" @click="updateChallengeStatus(c.id, 'rejected')">
                      <XCircle :size="12" /> Afwijzen
                    </button>
                  </template>
                  <button class="flex items-center gap-1.5 bg-gray-50 hover:bg-red-50 text-gray-400 hover:text-red-600 px-2.5 py-1.5 rounded-lg text-xs transition-colors border border-gray-200 hover:border-red-200" @click="deleteChallenge(c.id)">
                    <Trash2 :size="12" />
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div v-else-if="tab === 'news'">
          <div class="flex items-center justify-between mb-6">
            <div>
              <h2 class="text-xl font-bold text-gray-900">Nieuws</h2>
              <p class="text-sm text-gray-400 mt-0.5">{{ news.length }} berichten</p>
            </div>
            <button
              class="flex items-center gap-2 bg-roc-500 hover:bg-roc-600 text-white px-4 py-2.5 rounded-xl text-sm font-semibold transition-colors"
              @click="newsModalOpen = true; newsError = null"
            >
              <Plus :size="15" />
              Nieuwsbericht
            </button>
          </div>
          <div class="space-y-3">
            <div v-if="news.length === 0" class="text-center py-16 text-gray-400">
              <Newspaper :size="40" class="mx-auto mb-3 opacity-30" />
              <p class="font-medium">Nog geen nieuwsberichten.</p>
              <p class="text-xs mt-1">Klik op "Nieuwsbericht" om te beginnen.</p>
            </div>
            <div v-for="n in news" v-else :key="n.id" class="bg-white rounded-xl border border-gray-200 p-5 shadow-sm flex gap-4">
              <img v-if="n.image_url" :src="n.image_url" :alt="n.title" class="w-20 h-16 rounded-lg object-cover flex-shrink-0" />
              <div class="flex-1 min-w-0">
                <p class="text-gray-900 font-semibold text-sm mb-0.5">{{ n.title }}</p>
                <p v-if="n.excerpt" class="text-gray-400 text-xs line-clamp-1 mb-1">{{ n.excerpt }}</p>
                <p class="text-gray-300 text-xs">{{ fmtDateLong(n.created_at) }}</p>
              </div>
              <button
                class="flex items-center gap-1.5 bg-red-50 hover:bg-red-100 text-red-600 px-3 py-1.5 rounded-lg text-xs font-medium transition-colors border border-red-200 flex-shrink-0 self-start"
                @click="deleteNews(n.id)"
              >
                <Trash2 :size="12" /> Verwijderen
              </button>
            </div>
          </div>
        </div>

        <div v-else-if="tab === 'messages'">
          <div class="mb-6">
            <h2 class="text-xl font-bold text-gray-900">Contactberichten</h2>
            <p class="text-sm text-gray-400 mt-0.5">{{ messages.length }} berichten</p>
          </div>
          <div class="space-y-3">
            <div v-if="messages.length === 0" class="text-center py-16 text-gray-400">
              <Mail :size="40" class="mx-auto mb-3 opacity-30" />
              <p class="font-medium">Geen contactberichten.</p>
            </div>
            <div v-for="m in messages" v-else :key="m.id" class="bg-white rounded-xl border border-gray-200 p-5 shadow-sm">
              <div class="flex items-start justify-between gap-4">
                <div class="min-w-0 flex-1">
                  <div class="flex items-center gap-3 mb-0.5 flex-wrap">
                    <span class="text-gray-900 font-semibold text-sm">{{ m.name }}</span>
                    <a :href="`mailto:${m.email}`" class="text-roc-500 text-xs hover:underline">{{ m.email }}</a>
                  </div>
                  <p v-if="m.subject" class="text-gray-700 text-sm font-medium mb-2">{{ m.subject }}</p>
                  <p v-if="expandedMessage === m.id" class="text-gray-500 text-sm leading-relaxed">{{ m.message }}</p>
                  <p v-else class="text-gray-400 text-xs line-clamp-2">{{ m.message }}</p>
                </div>
                <button
                  class="flex items-center gap-1.5 bg-gray-50 hover:bg-gray-100 text-gray-500 px-3 py-1.5 rounded-lg text-xs font-medium transition-colors border border-gray-200 flex-shrink-0"
                  @click="toggleMessage(m.id)"
                >
                  <EyeOff v-if="expandedMessage === m.id" :size="12" />
                  <Eye v-else :size="12" />
                  {{ expandedMessage === m.id ? 'Inklappen' : 'Lees meer' }}
                </button>
              </div>
              <p class="text-gray-300 text-xs mt-3">{{ fmtDateTime(m.created_at) }}</p>
            </div>
          </div>
        </div>
      </template>
    </div>

    <Modal :is-open="newsModalOpen" title="Nieuwsbericht Plaatsen" @close="closeNewsModal">
      <form class="space-y-5" @submit="submitNews">
        <div v-if="newsError" class="flex items-center gap-2 bg-red-50 border border-red-200 rounded-lg p-3 text-red-600 text-sm">
          <AlertCircle :size="16" />
          {{ newsError }}
        </div>
        <div>
          <label class="block text-sm font-medium text-gray-700 mb-1.5">Titel <span class="text-red-500">*</span></label>
          <input v-model="newsForm.title" type="text" required placeholder="Titel van het nieuwsbericht" :class="inputClass" />
        </div>
        <div>
          <label class="block text-sm font-medium text-gray-700 mb-1.5">Samenvatting</label>
          <input v-model="newsForm.excerpt" type="text" placeholder="Korte samenvatting (optioneel)" :class="inputClass" />
        </div>
        <div>
          <label class="block text-sm font-medium text-gray-700 mb-1.5">Inhoud <span class="text-red-500">*</span></label>
          <textarea v-model="newsForm.content" required :rows="6" placeholder="Schrijf hier de volledige inhoud..." :class="`${inputClass} resize-none`" />
        </div>
        <div>
          <label class="block text-sm font-medium text-gray-700 mb-1.5">Afbeelding URL</label>
          <input v-model="newsForm.image_url" type="url" placeholder="https://images.pexels.com/..." :class="inputClass" />
        </div>
        <button
          type="submit" :disabled="newsSubmitting"
          class="w-full flex items-center justify-center gap-2 bg-roc-500 hover:bg-roc-600 disabled:bg-roc-300 text-white px-6 py-3 rounded-xl font-semibold transition-all"
        >
          <template v-if="newsSubmitting"><Loader2 :size="18" class="animate-spin" />Plaatsen...</template>
          <template v-else><Newspaper :size="18" />Nieuwsbericht Plaatsen</template>
        </button>
      </form>
    </Modal>
  </div>
</template>
